# Regression for the pipelined RV32I subset.
# Run every target from the project root: pipelined.sv does a relative
# $readmemh("memory.hex"), and the benches open their .hex files relative to
# the working directory too.
#
#   make        assemble all tests, build, run the 65-check core regression
#   make cache  build and run the D-cache benchmark suite
#   make icache build and run the I-cache benchmark suite
#   make vga    build and run the standalone VGA timing bench
#   make top    build and run the core-drives-VGA integration bench
#   make all3   all three, in order
#   make asm    re-assemble only (after editing processor/tests/*.s)
#   make wave   build with -DVCD, run, write wave.vcd for gtkwave
#   make ctest  compile C_compiled.c for RV32I and run it on the RTL
#   make cdisasm show the exact RV32I instructions generated by GCC
#   make isa    run the official riscv-tests rv32ui suite (isa_tests/run_isa.py)
#   make clean

SRCS  := processor/tb.sv processor/pipelined.sv
ASM   := $(wildcard processor/tests/*.s)
HEX   := $(ASM:.s=.hex)

C_CC      := riscv64-elf-gcc
C_OBJCOPY := riscv64-elf-objcopy
C_OBJDUMP := riscv64-elf-objdump
C_SRC     := C_test/C_compiled.c
C_START   := C_test/start.S
C_LINK    := C_test/link.ld
C_ELF     := C_test/program.elf
C_HEX     := C_test/program.hex
C_DATA_BIN   := C_test/program.data.bin
C_DATA_HEX   := C_test/data0.hex C_test/data1.hex C_test/data2.hex C_test/data3.hex
C_DATA_STAMP := C_test/data.stamp
C_FLAGS   := -march=rv32i -mabi=ilp32 -O2 -ffreestanding -nostdlib -nostartfiles -mno-relax -msmall-data-limit=0
C_EXPECT  ?= 10

.PHONY: all asm clean vga top all3 cache icache wave ctest ctest-data cdisasm isa FORCE
all: sim
	./sim

.PHONY: writeback
writeback:
	iverilog -g2012 -s tb_writeback -o sim_writeback processor/tb_writeback.sv processor/pipelined.sv
	vvp sim_writeback

.PHONY: branch
branch: $(HEX)
	python3 processor/bench/measure_branch.py

sim: $(SRCS) $(HEX)
	iverilog -g2012 -o sim $(SRCS)

asm: $(HEX)

processor/tests/%.hex: processor/tests/%.s asm.py
	python3 asm.py $< $@

# D-cache benchmarks: hit rate, miss rate, measured AMAT. No correctness
# checks here; tb.sv owns those.
BENCH_ASM := $(wildcard processor/bench/*.s)
BENCH_HEX := $(BENCH_ASM:.s=.hex)

.PHONY: associativity
associativity: $(HEX) $(BENCH_HEX)
	python3 processor/bench/measure_associativity.py

cache: processor/tb_cache.sv processor/pipelined.sv $(BENCH_HEX)
	iverilog -g2012 -o sim_cache processor/tb_cache.sv processor/pipelined.sv
	./sim_cache

processor/bench/%.hex: processor/bench/%.s asm.py
	python3 asm.py $< $@

# I-cache benchmark: fetch hit rate and cycles with the cache working vs
# defeated, on a few regression programs. No correctness checks here either.
icache: processor/tb_icache.sv processor/pipelined.sv $(HEX)
	iverilog -g2012 -o sim_icache processor/tb_icache.sv processor/pipelined.sv
	./sim_icache

# Standalone generator: VESA timing, sync polarity, blanking, bar count.
# No processor involved.
vga: vga/tb_vga.sv vga/vgagenerator.sv
	iverilog -g2012 -o sim_vga $^
	./sim_vga

# Integration: the core executes vgatest.hex and drives the generator's
# background colour through the 0x40C memory-mapped register.
top: vga/vgatest.hex vga/tb_top.sv processor/pipelined.sv vga/vgagenerator.sv
	iverilog -g2012 -o sim_top vga/tb_top.sv processor/pipelined.sv vga/vgagenerator.sv
	./sim_top

vga/vgatest.hex: vga/vgatest.s asm.py
	python3 asm.py $< $@

all3: all vga top

wave: $(SRCS) $(HEX)
	iverilog -g2012 -DVCD -o sim_wave $(SRCS)
	./sim_wave
	@echo "wrote wave.vcd -- view with: gtkwave wave.vcd"

# Bare-metal C: GCC produces an ELF, objcopy extracts instruction words, and
# tb_compiled treats ebreak as completion and checks main's return value in a0.
FORCE:

$(C_ELF): FORCE $(C_SRC) $(C_START) $(C_LINK)
	$(C_CC) $(C_FLAGS) -Wl,-T,$(C_LINK) $(C_START) $(C_SRC) -o $@

$(C_HEX): $(C_ELF)
	$(C_OBJCOPY) -O verilog --verilog-data-width=4 --only-section=.text $< $@

$(C_DATA_STAMP): $(C_ELF) C_test/split_data.py
	$(C_OBJCOPY) -O binary --only-section=.data $(C_ELF) $(C_DATA_BIN)
	python3 C_test/split_data.py $(C_DATA_BIN) C_test/data
	touch $@

ctest: $(C_HEX) $(C_DATA_STAMP) C_test/tb_compiled.sv processor/pipelined.sv
	iverilog -g2012 -DEXPECTED_RETURN=$(C_EXPECT) -o sim_c C_test/tb_compiled.sv processor/pipelined.sv
	./sim_c

ctest-data:
	$(MAKE) ctest C_SRC=C_test/initialized_data.c C_EXPECT=31

cdisasm: $(C_ELF)
	$(C_OBJDUMP) -d $(C_ELF)

# Official ISA suite. Vendored sources in isa_tests/vendor, custom env in
# isa_tests/env (this core has no CSRs), one plusarg-driven bench.
isa:
	python3 isa_tests/run_isa.py

clean:
	rm -f sim_writeback
	rm -rf isa_tests/build
	rm -f sim sim_vga sim_top sim_cache sim_icache sim_wave sim_c wave.vcd $(HEX) $(BENCH_HEX) vga/vgatest.hex $(C_ELF) $(C_HEX) $(C_DATA_BIN) $(C_DATA_HEX) $(C_DATA_STAMP)
